### ISSUE TITLE
Soul Speed Stops Working on Soul Sand

### ISSUE THREAD

**Issue by foxinacove** [Klyser8/Earthbounds#10]
For some reason, while I have this mod installed, the Soul Speed enchantment stops giving speed boost while walking on top of Soul Sand. It still works on Soul Soil. I don't suppose this is intentional, is it?

**Comment by Klyser8** [comment]
Issue should be fixed in 1.18.1-1.1.0a and 1.18.1-1.1.0b, thank you!
