### ISSUE TITLE
Mobs not turning red when hit

### ISSUE THREAD

**Issue by leonardsuedezu** [Klyser8/Earthbounds#17]
Hello, first off I want to say that I really like your mod, the content it adds really fits well with vanilla MC in my opinion. Keep up the good work!

One minor issue I've noticed is that Earthbounds' mobs don't turn red when taking damage. I have no other mods installed.

**Comment by Klyser8** [comment]
Hey, Earthen mobs (Pertilyos, Carboraneas and Rubros) don't turn red when hit with anything they are very resistant to. That's also accompanied by a sound effect. You should use Pickaxes or Flingshots against them!
