### ISSUE TITLE
Crashes when rendering entity

### ISSUE THREAD

**Issue by JustFoxx** [Klyser8/Earthbounds#2]
Crash logs: https://gist.github.com/NinjaPhenix/2ea9f8a4b7897584cb51243cfd0d66b4

**Comment by Klyser8** [comment]
Hey,
Can you tell me how you encountered this bug?

**Comment by JustFoxx** [comment]
this error wasnt from me, it was from person who was testing my modpack

**Comment by Klyser8** [comment]
Ah, I see. Could you ask them how they encountered this issue? It should be simple to fix, however I wouldn't want this to be part of bigger problem.

**Comment by JustFoxx** [comment]
@NinjaPhenix

**Comment by NinjaPhenix** [comment]
Had this issue, I just started a new world in Adventures Of Fox Beginning Of A Journey, broke a piece of grass and it stopped the internal server, since rejoining the world it hasn't crashed though so not sure how I could assist further...

**Comment by Klyser8** [comment]
Well, I'll just catch the error and have the game print out a warning instead of crashing. I'll release an update that fixes this soon, thank you!
