### ISSUE TITLE
Earthbounds latest version, crashes at starting

### ISSUE THREAD

**Issue by TheButterbrotMan** [Klyser8/Earthbounds#5]
https://bytebin.lucko.me/1B8QRGrvM0

**Comment by Klyser8** [comment]
There isn't anything that points to Earthbounds being at fault... What mods do you have installed? can you show the whole crash log?

**Comment by TheButterbrotMan** [comment]
It is the whole log, theres no crashlog, because it crashes directly after starting minecraft.

I switched back to 1.0.4a and now it works again.

**Comment by Klyser8** [comment]
It seems to be an issue with one of the mixins added in 1.0.5. I'll see what's going on and will get back to you soon!

**Comment by Klyser8** [comment]
Do you have the latest version of [ShethiPhianCore](https://www.curseforge.com/minecraft/mc-mods/shetiphiancore)?

**Comment by TheButterbrotMan** [comment]
yes

**Comment by Klyser8** [comment]
Alright, it's a compatibility issue with the mod it seems. Hopefully I will release a fix by tomorrow!

**Comment by Klyser8** [comment]
Issue resolved in 1.0.5a. Thank you for your help :)
